In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [54]:
dataset = pd.read_csv('/content/drive/MyDrive/ML WorkShop /dataset/salary.csv')

In [55]:
dataset

,age,education.num,capital.gain,hours.per.week,income
0,90,9,0,40,<=50K
1,82,9,0,18,<=50K
2,66,10,0,40,<=50K
3,54,4,0,40,<=50K
4,41,10,0,40,<=50K
...,...,...,...,...,...
32556,22,10,0,40,<=50K
32557,27,12,0,38,<=50K
32558,40,9,0,40,>50K
32559,58,9,0,40,<=50K


In [56]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   education.num   32561 non-null  int64 
 2   capital.gain    32561 non-null  int64 
 3   hours.per.week  32561 non-null  int64 
 4   income          32561 non-null  object
dtypes: int64(4), object(1)
memory usage: 1.2+ MB


In [57]:
dataset.isna().sum()

,0
age,0
education.num,0
capital.gain,0
hours.per.week,0
income,0


In [58]:
dataset.head(10)

,age,education.num,capital.gain,hours.per.week,income
0,90,9,0,40,<=50K
1,82,9,0,18,<=50K
2,66,10,0,40,<=50K
3,54,4,0,40,<=50K
4,41,10,0,40,<=50K
5,34,9,0,45,<=50K
6,38,6,0,40,<=50K
7,74,16,0,20,>50K
8,68,9,0,40,<=50K
9,41,10,0,60,>50K


In [59]:
dataset.iloc[101:201]

,age,education.num,capital.gain,hours.per.week,income
101,46,16,0,55,>50K
102,53,13,0,40,>50K
103,50,15,0,30,>50K
104,41,15,0,55,>50K
105,36,13,0,45,>50K
...,...,...,...,...,...
196,23,13,0,40,>50K
197,49,5,0,40,>50K
198,27,10,0,40,>50K
199,90,9,0,40,<=50K


In [60]:
dataset.iloc[:,[0,4]]

,age,income
0,90,<=50K
1,82,<=50K
2,66,<=50K
3,54,<=50K
4,41,<=50K
...,...,...
32556,22,<=50K
32557,27,<=50K
32558,40,>50K
32559,58,<=50K


In [61]:
dataset["income"].unique()

array(['<=50K', '>50K'], dtype=object)

In [62]:
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()

y = dataset['income']
dataset['income'] = label.fit_transform(y)
label.classes_

array(['<=50K', '>50K'], dtype=object)

In [63]:
dataset

,age,education.num,capital.gain,hours.per.week,income
0,90,9,0,40,0
1,82,9,0,18,0
2,66,10,0,40,0
3,54,4,0,40,0
4,41,10,0,40,0
...,...,...,...,...,...
32556,22,10,0,40,0
32557,27,12,0,38,0
32558,40,9,0,40,1
32559,58,9,0,40,0


In [64]:
x = dataset.iloc[:,:-1].values
x

array([[90,  9,  0, 40],
       [82,  9,  0, 18],
       [66, 10,  0, 40],
       ...,
       [40,  9,  0, 40],
       [58,  9,  0, 40],
       [22,  9,  0, 20]])

In [65]:
y = dataset.iloc[:,-1].values
y

array([0, 0, 0, ..., 1, 0, 0])

In [66]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)



In [67]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(26048, 4)
(6513, 4)
(26048,)
(6513,)


In [68]:
dataset['age'].min()

17

In [69]:
dataset['age'].max()


90

In [70]:
dataset['education.num'].min()


1

In [71]:
dataset['education.num'].max()


16

In [72]:
dataset['capital.gain'].min()


0

In [73]:
dataset['capital.gain'].max()


99999

In [74]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [75]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=2,metric='minkowski')
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [76]:
y_pred = knn.predict(x_test)


In [77]:
# print("accuracy is :",format(knn.score(y_test,y_pred)*100))

In [79]:
Age = int(input("Enter Age : "))
Education_num = int(input("Enter Education Num : "))
capital_gain = int(input("Enter Capital Gain : "))
working_hours = int(input("Enter Working Hours : "))

newemp = [[Age,Education_num,capital_gain,working_hours]]

result = knn.predict(sc.transform(newemp))

print(result)

if result == 1 :
  print("Employee might have salary above 50k")
else:
  print("Employee might not have salary above 50k")


Enter Age : 60
Enter Education Num : 40
Enter Capital Gain : 30
Enter Working Hours : 20
[1]
Employee might have salary aboue 50k


In [81]:
from sklearn.metrics import confusion_matrix , accuracy_score

cm = confusion_matrix(y_test,y_pred)

print("confusion matrix :")
print(cm)

print("accuracy of : {0}%".format(accuracy_score(y_test,y_pred)*100))

confusion matrix :
[[4757  219]
 [1084  453]]
accuracy of : 79.9938584369722%


In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data_set = pd.read_csv('/content/drive/MyDrive/ML WorkShop /dataset/users.csv')


In [84]:
data_set

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,12,19000,0
1,15810944,Male,11,20000,0
2,15668575,Female,1,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,10,76000,0
...,...,...,...,...,...
94,15786993,Female,45,83000,0
95,15709441,Female,35,44000,0
96,15710257,Female,4,25000,0
97,15582492,Male,5,123000,1


In [85]:
data_set.isna().sum()

,0
User ID,0
Gender,0
Age,0
EstimatedSalary,0
Purchased,0


In [86]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          99 non-null     int64 
 1   Gender           99 non-null     object
 2   Age              99 non-null     int64 
 3   EstimatedSalary  99 non-null     int64 
 4   Purchased        99 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 4.0+ KB


In [87]:
data_set.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,12,19000,0
1,15810944,Male,11,20000,0
2,15668575,Female,1,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,10,76000,0


In [89]:
data_set['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [90]:
data_set['Purchased'].unique()


array([0, 1])

In [93]:
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()

y = dataset['Gender']
dataset['Gender'] = label.fit_transform(y)
label.classes_

array([0, 1])

In [94]:
x = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,4].values

In [95]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)


In [96]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train
x_test

array([[-0.40281429, -0.94975175],
       [ 1.17992506, -0.10674686],
       [-0.79849913, -0.4814157 ],
       [-0.79849913, -0.10674686],
       [ 2.23508462,  1.67293011],
       [-0.27091935, -1.35564299],
       [-0.40281429, -1.04341896],
       [ 2.63076946,  1.70415251],
       [-0.79849913, -0.01307966],
       [ 2.10318968,  0.76748042],
       [-0.1390244 , -1.10586376],
       [ 1.70750484,  1.79781972],
       [-0.40281429,  0.89237003],
       [-0.27091935, -1.26197578],
       [-0.00712946,  2.85938142],
       [-0.40281429,  0.48647879],
       [-0.79849913, -0.54386051],
       [-0.66660419, -1.10586376],
       [-0.79849913, -0.4501933 ],
       [-0.27091935, -0.79363973],
       [-0.79849913, -1.35564299],
       [ 1.04803011,  0.23669957],
       [ 1.44371495, -0.04430206],
       [-0.79849913, -0.98097415],
       [-0.79849913, -1.19953097]])

In [97]:
from sklearn.svm import SVC

classifier = SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
# from matplotlib.colors import ListedColormap
# x_set,y_set = x_train,y_train

# x1,y1 = np.meshgrid(np.arange(start = x_set[:,0].min() - 1 ,))