The python package Numpy, which stands for "Numerical Python"

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


In [3]:
l1 = [1,2,3,4,5]
#print(l1)
l1

[1, 2, 3, 4, 5]

In [4]:
x=np.array(l1)
x

array([1, 2, 3, 4, 5])

find the diffrence between list and numpy array

In [5]:
#create 1D array
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [6]:
x=np.random.rand(5)
x

array([0.32319723, 0.12833906, 0.99518367, 0.57170902, 0.8534592 ])

In [7]:
x=np.random.randint(5,16,10)
print(x)

[ 5  5 11 12  8  6 11  9  9 14]


In [8]:
#2D array
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [9]:
y=np.random.rand(3,4)
print(y)

[[0.04621574 0.87706977 0.08252662 0.55426858]
 [0.90457236 0.41680141 0.23752244 0.54726783]
 [0.06855921 0.54707853 0.83170364 0.89805819]]


In [10]:
y=np.random.randint(5,16,(3,3))
print(y)

[[15 12  8]
 [13  6  8]
 [15 12  5]]


In [11]:
n = int(input())
for i in range(1,n+1):
    for j in range(1,i+1):
        print("*",end="")
    print()

*
**
***
****
*****


In [12]:
#3D array
z=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(z)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a=np.ones((3,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
a=np.full((5,5),7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [16]:
a=np.eye(4,5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [17]:
print("Shape of  array:",a.shape)

Shape of  array: (4, 5)


In [18]:
z.ndim

3

In [19]:
a.size

20

In [20]:
a.dtype

dtype('int64')

In [21]:
x.min()

np.int64(5)

In [22]:
x.max()

np.int64(14)

In [23]:
x.argmin()

np.int64(0)

In [24]:
x.argmax()

np.int64(9)

In [25]:
x.mean()

np.float64(9.0)

In [26]:
a=np.random.randint(1,10,(2,2)*2)
print(a)

[[[[1 4]
   [1 9]]

  [[8 6]
   [7 3]]]


 [[[2 5]
   [4 3]]

  [[1 7]
   [6 3]]]]


In [27]:
a.sum(axis=0)

array([[[ 3,  9],
        [ 5, 12]],

       [[ 9, 13],
        [13,  6]]])

Indexing is the process of accessing a single element from a sequence using its position or index.
it retrives a single element at a specific position.

Slicing refers to the process of extracting a portion of an array or a subarray. 
it allows you to access specific element or range of element in a Numpy array

give a diffrence between indexing and slicing ??

In [28]:
x[2]

np.int64(11)

In [29]:
x[-2]

np.int64(9)

In [30]:
y

array([[15, 12,  8],
       [13,  6,  8],
       [15, 12,  5]])

In [31]:
y[0,2]

np.int64(8)

In [32]:
x

array([ 5,  5, 11, 12,  8,  6, 11,  9,  9, 14])

In [33]:
x[2:5]

array([11, 12,  8])

In [34]:
x[:5]

array([ 5,  5, 11, 12,  8])

In [35]:
x[5]=100

In [36]:
x

array([  5,   5,  11,  12,   8, 100,  11,   9,   9,  14])

In [37]:
x[1:8:2]

array([  5,  12, 100,   9])

In [38]:
np.flip(x)

array([ 14,   9,   9,  11, 100,   8,  12,  11,   5,   5])

In [39]:
x[:]=200
x

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [40]:
import pandas as pd 

Pandas is an open-source library for real world data analysis in python. it is build on top of numpy.

Using pandas, data can be cleaned , transformed , manipulated and analized.



1. Series object series is a one dimentional labled array. It supports diffrent data type like integer , float , string etc..

2. DataFram 

A DataFram in pandas is a two-dimensial , tabular data structure similar to a spreadsheet or SOL table.

It consists of rows and column where:

column : 

In [41]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [42]:
s2 = pd.Series([10,20,30,40,50], index=['A','B','C','D','E'])
s2

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [43]:
s1.values

array([10, 20, 30, 40, 50])

In [44]:
s2.values

array([10, 20, 30, 40, 50])

In [45]:
s2.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [46]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [47]:
data = [{'Name':'subodh','Marks':28},
        {'Name':'Ram','Marks':27},
        {'Name':'abdul','Marks':26},
        {'Name':'john','Marks':28}]
f1=pd.DataFrame(data)
f1

Name  Marks
0  subodh     28
1     Ram     27
2   abdul     26
3    john     28

In [48]:
data

[{'Name': 'subodh', 'Marks': 28},
 {'Name': 'Ram', 'Marks': 27},
 {'Name': 'abdul', 'Marks': 26},
 {'Name': 'john', 'Marks': 28}]

In [50]:
print(f1)

     Name  Marks
0  subodh     28
1     Ram     27
2   abdul     26
3    john     28


In [51]:
type(f1)

pandas.core.frame.DataFrame

In [52]:
type(data)

list

In [59]:
data = pd.read_csv('Iris.csv')
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [62]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [63]:
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [64]:
data.index

RangeIndex(start=0, stop=150, step=1)

In [67]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [68]:
cat = data['Species'].unique()

In [69]:
cat

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [70]:
data.replace("Iris-setosa","setosa",inplace=True)

In [71]:
data.replace("Iris-virsicolor","virsicolor",inplace=True)

In [74]:
data.replace("Iris-virginica","virginica",inplace=True)

In [75]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
0      1            5.1           3.5            1.4           0.2     setosa
1      2            4.9           3.0            1.4           0.2     setosa
2      3            4.7           3.2            1.3           0.2     setosa
3      4            4.6           3.1            1.5           0.2     setosa
4      5            5.0           3.6            1.4           0.2     setosa
..   ...            ...           ...            ...           ...        ...
145  146            6.7           3.0            5.2           2.3  virginica
146  147            6.3           2.5            5.0           1.9  virginica
147  148            6.5           3.0            5.2           2.0  virginica
148  149            6.2           3.4            5.4           2.3  virginica
149  150            5.9           3.0            5.1           1.8  virginica

[150 rows x 6 columns]

In [76]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [80]:
data[['SepalLengthCm','SepalWidthCm']].head(10)

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6
5            5.4           3.9
6            4.6           3.4
7            5.0           3.4
8            4.4           2.9
9            4.9           3.1