The python package Numpy, which stands for "Numerical Python"

In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.2.6


In [5]:
l1 = [1,2,3,4,5]
#print(l1)
l1

[1, 2, 3, 4, 5]

In [6]:
x=np.array(l1)
x

array([1, 2, 3, 4, 5])

find the diffrence between list and numpy array

In [7]:
#create 1D array
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [8]:
x=np.random.rand(5)
x

array([0.21027191, 0.33118142, 0.77839841, 0.44757093, 0.7083033 ])

In [9]:
x=np.random.randint(5,16,10)
print(x)

[10 12  5  9  8 10  7 14 11  5]


In [10]:
#2D array
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [11]:
y=np.random.rand(3,4)
print(y)

[[0.01417151 0.67389491 0.37681486 0.45288959]
 [0.42563321 0.18119498 0.94927649 0.37380495]
 [0.82244942 0.36298844 0.34012984 0.91434558]]


In [12]:
y=np.random.randint(5,16,(3,3))
print(y)

[[10  5  5]
 [15 13  6]
 [ 6 12 14]]


In [13]:
n = int(input())
for i in range(1,n+1):
    for j in range(1,i+1):
        print("*",end="")
    print()

*
**
***
****
*****


In [14]:
#3D array
z=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(z)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a=np.ones((3,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
a=np.full((5,5),7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [18]:
a=np.eye(4,5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [19]:
print("Shape of  array:",a.shape)

Shape of  array: (4, 5)


In [20]:
z.ndim

3

In [21]:
a.size

20

In [22]:
a.dtype

dtype('int64')

In [23]:
x.min()

np.int64(5)

In [24]:
x.max()

np.int64(14)

In [25]:
x.argmin()

np.int64(2)

In [26]:
x.argmax()

np.int64(7)

In [27]:
x.mean()

np.float64(9.1)

In [28]:
a=np.random.randint(1,10,(2,2)*2)
print(a)

[[[[9 9]
   [3 6]]

  [[3 7]
   [9 5]]]


 [[[8 2]
   [6 2]]

  [[6 6]
   [2 1]]]]


In [29]:
a.sum(axis=0)

array([[[17, 11],
        [ 9,  8]],

       [[ 9, 13],
        [11,  6]]])

Indexing is the process of accessing a single element from a sequence using its position or index.
it retrives a single element at a specific position.

Slicing refers to the process of extracting a portion of an array or a subarray. 
it allows you to access specific element or range of element in a Numpy array

give a diffrence between indexing and slicing ??

In [30]:
x[2]

np.int64(5)

In [31]:
x[-2]

np.int64(11)

In [32]:
y

array([[10,  5,  5],
       [15, 13,  6],
       [ 6, 12, 14]])

In [33]:
y[0,2]

np.int64(5)

In [34]:
x

array([10, 12,  5,  9,  8, 10,  7, 14, 11,  5])

In [35]:
x[2:5]

array([5, 9, 8])

In [36]:
x[:5]

array([10, 12,  5,  9,  8])

In [37]:
x[5]=100

In [38]:
x

array([ 10,  12,   5,   9,   8, 100,   7,  14,  11,   5])

In [39]:
x[1:8:2]

array([ 12,   9, 100,  14])

In [40]:
np.flip(x)

array([  5,  11,  14,   7, 100,   8,   9,   5,  12,  10])

In [41]:
x[:]=200
x

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [42]:
import pandas as pd 

Pandas is an open-source library for real world data analysis in python. it is build on top of numpy.

Using pandas, data can be cleaned , transformed , manipulated and analized.



1. Series object series is a one dimentional labled array. It supports diffrent data type like integer , float , string etc..

2. DataFram 

A DataFram in pandas is a two-dimensial , tabular data structure similar to a spreadsheet or SOL table.

It consists of rows and column where:

column : 

In [43]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [44]:
s2 = pd.Series([10,20,30,40,50], index=['A','B','C','D','E'])
s2

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [45]:
s1.values

array([10, 20, 30, 40, 50])

In [46]:
s2.values

array([10, 20, 30, 40, 50])

In [47]:
s2.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [48]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [49]:
data = [{'Name':'subodh','Marks':28},
        {'Name':'Ram','Marks':27},
        {'Name':'abdul','Marks':26},
        {'Name':'john','Marks':28}]
f1=pd.DataFrame(data)
f1

Name  Marks
0  subodh     28
1     Ram     27
2   abdul     26
3    john     28

In [50]:
data

[{'Name': 'subodh', 'Marks': 28},
 {'Name': 'Ram', 'Marks': 27},
 {'Name': 'abdul', 'Marks': 26},
 {'Name': 'john', 'Marks': 28}]

In [51]:
print(f1)

     Name  Marks
0  subodh     28
1     Ram     27
2   abdul     26
3    john     28


In [52]:
type(f1)

pandas.core.frame.DataFrame

In [53]:
type(data)

list

In [90]:
data = pd.read_csv('dataset/iris.csv')
data

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [55]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [56]:
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [57]:
data.index

RangeIndex(start=0, stop=150, step=1)

In [58]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [59]:
cat = data['Species'].unique()

In [60]:
cat

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [61]:
data.replace("Iris-setosa","setosa",inplace=True)

In [62]:
data.replace("Iris-virsicolor","virsicolor",inplace=True)

In [63]:
data.replace("Iris-virginica","virginica",inplace=True)

In [64]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
0      1            5.1           3.5            1.4           0.2     setosa
1      2            4.9           3.0            1.4           0.2     setosa
2      3            4.7           3.2            1.3           0.2     setosa
3      4            4.6           3.1            1.5           0.2     setosa
4      5            5.0           3.6            1.4           0.2     setosa
..   ...            ...           ...            ...           ...        ...
145  146            6.7           3.0            5.2           2.3  virginica
146  147            6.3           2.5            5.0           1.9  virginica
147  148            6.5           3.0            5.2           2.0  virginica
148  149            6.2           3.4            5.4           2.3  virginica
149  150            5.9           3.0            5.1           1.8  virginica

[150 rows x 6 columns]

In [65]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [66]:
data[['SepalLengthCm','SepalWidthCm']].head(10)

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6
5            5.4           3.9
6            4.6           3.4
7            5.0           3.4
8            4.4           2.9
9            4.9           3.1

In [71]:
def yea_no(SepalLengthCm):
    return 'YES' if SepalLengthCm >= 5 else 'NO'

data['Result'] = data['SepalLengthCm'].apply(yea_no)
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species  \
0      1            5.1           3.5            1.4           0.2     setosa   
1      2            4.9           3.0            1.4           0.2     setosa   
2      3            4.7           3.2            1.3           0.2     setosa   
3      4            4.6           3.1            1.5           0.2     setosa   
4      5            5.0           3.6            1.4           0.2     setosa   
..   ...            ...           ...            ...           ...        ...   
145  146            6.7           3.0            5.2           2.3  virginica   
146  147            6.3           2.5            5.0           1.9  virginica   
147  148            6.5           3.0            5.2           2.0  virginica   
148  149            6.2           3.4            5.4           2.3  virginica   
149  150            5.9           3.0            5.1           1.8  virginica   

    Result  
0      YES  
1       NO  
2       NO  
3       NO  
4      YES  
..     ...  
145    YES  
146    YES  
147    YES  
148    YES  
149    YES  

[150 rows x 7 columns]

In [75]:
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species', 'Result'],
      dtype='object')

The .iloc indexer is primarily used for integer-location based indexing

In [76]:
data.drop('Result',axis=1,inplace=True)

In [77]:
data.iloc[51:56,2:5]

SepalWidthCm  PetalLengthCm  PetalWidthCm
51           3.2            4.5           1.5
52           3.1            4.9           1.5
53           2.3            4.0           1.3
54           2.8            4.6           1.5
55           2.8            4.5           1.3

In [ ]:
data[data['PetalLengthCm']>5]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
83    84            6.0           2.7            5.1           1.6   
100  101            6.3           3.3            6.0           2.5   
101  102            5.8           2.7            5.1           1.9   
102  103            7.1           3.0            5.9           2.1   
103  104            6.3           2.9            5.6           1.8   
104  105            6.5           3.0            5.8           2.2   
105  106            7.6           3.0            6.6           2.1   
107  108            7.3           2.9            6.3           1.8   
108  109            6.7           2.5            5.8           1.8   
109  110            7.2           3.6            6.1           2.5   
110  111            6.5           3.2            5.1           2.0   
111  112            6.4           2.7            5.3           1.9   
112  113            6.8           3.0            5.5           2.1   
114  115            5.8           2.8            5.1           2.4   
115  116            6.4           3.2            5.3           2.3   
116  117            6.5           3.0            5.5           1.8   
117  118            7.7           3.8            6.7           2.2   
118  119            7.7           2.6            6.9           2.3   
120  121            6.9           3.2            5.7           2.3   
122  123            7.7           2.8            6.7           2.0   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

             Species  
83   Iris-versicolor  
100        virginica  
101        virginica  
102        virginica  
103        virginica  
104        virginica  
105        virginica  
107        virginica  
108        virginica  
109        virginica  
110        virginica  
111        virginica  
112        virginica  
114        virginica  
115        virginica  
116        virginica  
117        virginica  
118        virginica  
120        virginica  
122        virginica  
124        virginica  
125        virginica  
128        virginica  
129        virginica  
130        virginica  
131        virginica  
132        virginica  
133        virginica  
134        virginica  
135        virginica  
136        virginica  
137        virginica  
139        virginica  
140        virginica  
141        virginica  
142        virginica  
143        virginica  
144        virginica  
145        virginica  
147        virginica  
148        virginica  
149        virginica

In [81]:
data[(data['PetalLengthCm']>6) & (data['Species'] == 'virginica')]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
105  106            7.6           3.0            6.6           2.1  virginica
107  108            7.3           2.9            6.3           1.8  virginica
109  110            7.2           3.6            6.1           2.5  virginica
117  118            7.7           3.8            6.7           2.2  virginica
118  119            7.7           2.6            6.9           2.3  virginica
122  123            7.7           2.8            6.7           2.0  virginica
130  131            7.4           2.8            6.1           1.9  virginica
131  132            7.9           3.8            6.4           2.0  virginica
135  136            7.7           3.0            6.1           2.3  virginica

In [88]:
data.duplicated().sum()

np.int64(0)

In [91]:
student = pd.read_csv('dataset/student_info.csv')
student

study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]

In [92]:
student.columns

Index(['study_hours', 'student_marks'], dtype='object')

In [93]:
student.info

<bound method DataFrame.info of      study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]>

In [94]:
student.head()

study_hours  student_marks
0         6.83          78.50
1         6.56          76.74
2          NaN          78.68
3         5.67          71.82
4         8.67          84.19

In [95]:
student.tail()

study_hours  student_marks
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

In [100]:
student.isnull().sum()

study_hours      5
student_marks    0
dtype: int64

In [101]:
student['study_hours']=student['study_hours'].fillna(student['study_hours'].mean())

In [104]:
student.isna().sum()

study_hours      0
student_marks    0
dtype: int64

In [114]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 

iris

{'data': {'ids': None,
  'features':      sepal length  sepal width  petal length  petal width
  0             5.1          3.5           1.4          0.2
  1             4.9          3.0           1.4          0.2
  2             4.7          3.2           1.3          0.2
  3             4.6          3.1           1.5          0.2
  4             5.0          3.6           1.4          0.2
  ..            ...          ...           ...          ...
  145           6.7          3.0           5.2          2.3
  146           6.3          2.5           5.0          1.9
  147           6.5          3.0           5.2          2.0
  148           6.2          3.4           5.4          2.3
  149           5.9          3.0           5.1          1.8
  
  [150 rows x 4 columns],
  'targets':               class
  0       Iris-setosa
  1       Iris-setosa
  2       Iris-setosa
  3       Iris-setosa
  4       Iris-setosa
  ..              ...
  145  Iris-virginica
  146  Iris-virginica
  147  